"""init

Revision ID: 783987c926b4
Revises: 
Create Date: 2025-11-28 15:50:47.660679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '783987c926b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versioncomparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_first', sa.String(), nullable=False),
    sa.Column('version_second', sa.String(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versioncomparisons_version_first'), 'versioncomparisons', ['version_first'], unique=False)
    op.create_index(op.f('ix_versioncomparisons_version_second'), 'versioncomparisons', ['version_second'], unique=False)
    op.create_table('versionfiles',
    sa.Column('version_name', sa.String(), nullable=False),
    sa.Column('path_to_hits', sa.String(), nullable=False),
    sa.Column('path_to_visits', sa.String(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('version_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('versionfiles')
    op.drop_index(op.f('ix_versioncomparisons_version_second'), table_name='versioncomparisons')
    op.drop_index(op.f('ix_versioncomparisons_version_first'), table_name='versioncomparisons')
    op.drop_table('versioncomparisons')
    # ### end Alembic commands ###
